version: "3.8"
services:
  front:
    container_name: front
    build:
      context: ./conference
      args:
        VITE_API_URL: ${VITE_API_URL}
    depends_on: 
      - back
    ports:
      - 80:80
    networks:
      - conference-net
    environment:
      - NODE_ENV=production
    restart: on-failure:2
  back:
    container_name: back
    build:
      context: ./ConferenceManager
      args:
        DB_SERVER: ${DB_SERVER}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${MSSQL_SA_PASSWORD}
        TOKEN_ISSUER: ${TOKEN_ISSUER}
        TOKEN_AUDIENCE: ${TOKEN_AUDIENCE}
        TOKEN_KEY: ${TOKEN_KEY}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        FRONT_URL: ${TOKEN_AUDIENCE}
    depends_on: 
      - db
    ports:
      - 8000:8000
    networks:
      - conference-net
    restart: on-failure:2
  db: 
    container_name: db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    networks:
      - conference-net
    volumes:
      - db-data-vol:/var/opt/mssql
      - db-backup-vol:/backup
    user: root
    environment:
      - ACCEPT_EULA=Y      
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Express 
    restart: on-failure:2
  backup:
    container_name: backup
    image: bbtsoftwareag/mssql-backup
    depends_on: 
      - db
    volumes:
      - db-backup-vol:/backup
    environment:
      - TZ=Europe/Kiev
      - DB_SERVER=${DB_SERVER}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${MSSQL_SA_PASSWORD}
      - DB_NAMES=ConferenceManager
      - BACKUP_CLEANUP=true
      - BACKUP_AGE=10
      - CRON_SCHEDULE=0 0 * * *
    networks:
      - conference-net

volumes:
  db-data-vol: 
  db-backup-vol:   

networks:
  conference-net: