version: "3.8"
services:
  ms-front:
    container_name: ms-front
    build:
      context: ./conference
      args:
        VITE_USER_API_URL: ${VITE_USER_API_URL}
        VITE_CONFERENCE_API_URL: ${VITE_CONFERENCE_API_URL}
        VITE_SUBMISSION_API_URL: ${VITE_SUBMISSION_API_URL}
    ports:
      - 80:80
    networks:
      - conference-net
    environment:
      - NODE_ENV=production
    restart: on-failure:2
  user-service:
    container_name: user-service
    build:
      context: ./ConferenceManager/
      args:
        DB_SERVER: ${DB_SERVER}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${MSSQL_SA_PASSWORD}
        TOKEN_ISSUER: ${TOKEN_ISSUER}
        TOKEN_AUDIENCE: ${TOKEN_AUDIENCE}
        TOKEN_KEY: ${TOKEN_KEY}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        FRONT_URL: ${TOKEN_AUDIENCE}
        PROJECT: User
        PORT: 8001
    depends_on: 
      - db
    ports:
      - 8001:8001
    networks:
      - conference-net
    restart: on-failure:2
  conference-service:
    container_name: conference-service
    build:
      context: ./ConferenceManager/
      args:
        DB_SERVER: ${DB_SERVER}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${MSSQL_SA_PASSWORD}
        TOKEN_ISSUER: ${TOKEN_ISSUER}
        TOKEN_AUDIENCE: ${TOKEN_AUDIENCE}
        TOKEN_KEY: ${TOKEN_KEY}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        FRONT_URL: ${TOKEN_AUDIENCE}
        PROJECT: Conference
        PORT: 8002
    depends_on: 
      - user-service
    ports:
      - 8002:8002
    networks:
      - conference-net
    restart: on-failure:2
  submission-service:
    container_name: submission-service
    build:
      context: ./ConferenceManager/
      args:
        DB_SERVER: ${DB_SERVER}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${MSSQL_SA_PASSWORD}
        TOKEN_ISSUER: ${TOKEN_ISSUER}
        TOKEN_AUDIENCE: ${TOKEN_AUDIENCE}
        TOKEN_KEY: ${TOKEN_KEY}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        FRONT_URL: ${TOKEN_AUDIENCE}
        PROJECT: Submission
        PORT: 8003
    depends_on: 
      - user-service
      - db
    ports:
      - 8003:8003
    networks:
      - conference-net
    restart: on-failure:2
  db: 
    container_name: db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    networks:
      - conference-net
    volumes:
      - db-data-vol:/var/opt/mssql
      - db-backup-vol:/backup
    user: root
    environment:
      - ACCEPT_EULA=Y      
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Express 
    restart: on-failure:2
  backup:
    container_name: backup
    image: bbtsoftwareag/mssql-backup
    depends_on: 
      - db
    volumes:
      - db-backup-vol:/backup
    environment:
      - TZ=Europe/Kiev
      - DB_SERVER=${DB_SERVER}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${MSSQL_SA_PASSWORD}
      - DB_NAMES=ConferenceManager
      - BACKUP_CLEANUP=true
      - BACKUP_AGE=10
      - CRON_SCHEDULE=0 0 * * *
    networks:
      - conference-net

volumes:
  db-data-vol: 
  db-backup-vol:   

networks:
  conference-net: