export type Conference = {
    id: number,
    userid: number,
    title: string,
    keywords: string,
    abstract: string,
    createdon: Date,
    updatedon: Date,
    acronym: string,
    webpage: string,
    venue: string,
    city: string,
    start: Date,
    end: Date,
    primaryResearchArea: string,
    secondaryResearchArea: string,
    areaNotes: string,
    organizer: string,
    organizerWebpage: string,
    contactPhoneNumber: string
};